# Generated by Django 5.2.8 on 2025-11-27 04:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField(default='')),
                ('schema', models.JSONField(default=dict)),
                ('code_bundle_url', models.TextField(blank=True, null=True)),
                ('llm_provider', models.CharField(choices=[('groq', 'Groq'), ('gemini', 'Gemini'), ('openai', 'OpenAI')], max_length=30)),
                ('token_usage', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='projects.project')),
            ],
        ),
    ]
