# Generated by Django 5.2.8 on 2025-12-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generations',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
