# Generated by Django 5.2.8 on 2026-02-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0002_generations_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='generations',
            name='ai_response',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
