# Generated by Django 5.2.8 on 2026-01-05 10:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generation', '0002_generations_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patch_data', models.JSONField(help_text='JSON Patch operations (RFC 6902 format)')),
                ('description', models.CharField(blank=True, help_text='Optional description of what this patch changes', max_length=500)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot_created', models.BooleanField(default=False, help_text='Whether a snapshot was created after this patch')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patches', to='generation.generations')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['generation', '-applied_at'], name='patching_pa_generat_c2974f_idx'), models.Index(fields=['user', '-applied_at'], name='patching_pa_user_id_f2e34f_idx')],
            },
        ),
    ]
