"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta
import dj_database_url


load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

APP_MODE = str(os.environ.get("APP_MODE", 'Development'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False") == "True"

ALLOWED_HOSTS = os.environ.get(
    "ALLOWED_HOSTS",
    "localhost,127.0.0.1"
).split(",")

CORS_ALLOW_CREDENTIALS = os.environ.get("CORS_ALLOW_CREDENTIALS", "True") == "True"
CORS_ALLOWED_ORIGINS = os.environ.get(
    "CORS_ALLOWED_ORIGINS",
    "https://dburst-ui-generator.vercel.app,"
    "http://localhost:5173,"
    "https://localhost:5173"
).split(",")

CSRF_TRUSTED_ORIGINS = os.environ.get(
    "CSRF_TRUSTED_ORIGINS",
    "https://dburst-ui-generator.vercel.app,"
    "https://dburst-ui-generator.onrender.com,"
    "http://localhost:5173,"
    "https://localhost:5173"
).split(",")

CORS_ALLOW_HEADERS = os.environ.get(
    "CORS_ALLOW_HEADERS",
    "accept,"
    "accept-encoding,"
    "authorization,"
    "content-type,"
    "dnt,"
    "origin,"
    "user-agent,"
    "x-csrftoken,"
    "x-requested-with,"
    "ngrok-skip-browser-warning"
).split(",")

# 1 day for access, 7 days for refresh
ACCESS_TOKEN_EXPIRY = 86400
REFRESH_TOKEN_EXPIRY = 604800

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # local apps
    'users',
    'otp_auth',
    'projects',
    'generation',
    'patching',
    'feedback',
    
    # third party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'rest_framework.authtoken',
    'corsheaders',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'dj_rest_auth',
    'dj_rest_auth.registration',
    # Enables runserver_plus and other Django extension commands.
    'django_extensions',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.environ.get("DATABASE_URL")

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(default=DATABASE_URL)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'config.authentication.CookieJWTAuthentication', 
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

AUTH_USER_MODEL = "users.User"

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.environ.get("REDIS_URL", "redis://127.0.0.1:6379/1"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CLOSE_CONNECTION": True,
        }
    }
}

# ========================================
# SESSION CONFIGURATION (REDIS-BACKED)
# ========================================

# Use Redis for session storage
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

# Session Security Settings
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Cookies marked Secure are silently dropped by the browser unless the
# response that sets them came over HTTPS, and SameSite=None requires
# Secure or the cookie gets rejected outright — the two must move together.
# Production (Render/Vercel, both HTTPS) wants True/None, which is the
# default here. Local dev runs the backend over plain HTTP (see run.sh),
# so backend/.env overrides these to False/Lax — same-site is still true
# for localhost:5173 <-> localhost:8000 (same scheme + hostname, just a
# different port), so Lax cookies still flow on cross-port XHR fine.
COOKIE_SECURE = os.environ.get("COOKIE_SECURE", "True") == "True"
COOKIE_SAMESITE = os.environ.get("COOKIE_SAMESITE", "None")

SESSION_COOKIE_SECURE = COOKIE_SECURE
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookie
SESSION_COOKIE_SAMESITE = COOKIE_SAMESITE
CSRF_COOKIE_SECURE = COOKIE_SECURE
CSRF_COOKIE_SAMESITE = COOKIE_SAMESITE
SESSION_COOKIE_NAME = 'dburst_sessionid'  # Custom session cookie name
SESSION_COOKIE_PATH = '/'
SESSION_COOKIE_DOMAIN = None  # Use default domain

# Session Timeout Settings
SESSION_COOKIE_AGE = 86400 * 7  # 7 days (in seconds)
SESSION_SAVE_EVERY_REQUEST = False  # Only save if session modified
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Persist sessions

# Session Serialization
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer'

# ========================================
# CACHE TIMEOUT SETTINGS
# ========================================

# Cache timeouts for different data types
CACHE_TTL = {
    'generation_schema': 86400 * 3,  # 3 days
    'generation_code': 86400 * 3,    # 3 days
    'generation_meta': 86400 * 3,    # 3 days
    'patches': 86400 * 7,            # 7 days
    'session': 86400 * 7,            # 7 days
    'user_profile': 3600,            # 1 hour
    'project_list': 300,             # 5 minutes
}

# ========================================
# OAUTH & API KEYS
# ========================================

GOOGLE_CLIENT_ID = os.environ.get("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = os.environ.get("GOOGLE_CLIENT_SECRET")

GITHUB_CLIENT_ID = os.environ.get("GITHUB_CLIENT_ID")
GITHUB_CLIENT_SECRET = os.environ.get("GITHUB_CLIENT_SECRET")

# Whitelisted redirect URIs — backend validates against these.
# Add your production URL and any local dev URLs here.
# NOTE: 'postmessage' was used for popup flow — removed in favour of redirect flow
# which is compatible with Cross-Origin-Opener-Policy: same-origin (WebContainer).
_google_uris = os.environ.get(
    "GOOGLE_ALLOWED_REDIRECT_URIS",
    "http://localhost:5173/auth/google/callback,"
    "https://localhost:5173/auth/google/callback,"
    "https://dburst-ui-generator.onrender.com/auth/google/callback,"
    "https://dburst-ui-generator.vercel.app/auth/google/callback"
)
GOOGLE_ALLOWED_REDIRECT_URIS = [u.strip() for u in _google_uris.split(",") if u.strip()]

_github_uris = os.environ.get(
    "GITHUB_ALLOWED_REDIRECT_URIS",
    "http://localhost:5173/auth/github/callback,"
    "https://localhost:5173/auth/github/callback,"
    "https://dburst-ui-generator.onrender.com/auth/github/callback,"
    "https://dburst-ui-generator.vercel.app/auth/github/callback"
)
GITHUB_ALLOWED_REDIRECT_URIS = [u.strip() for u in _github_uris.split(",") if u.strip()]

GROQ_AI_API_KEY = os.environ.get("GROQ_AI_API_KEY")
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")

# Selectable UI-generation models per provider, plus the "reasoning"/planner
# model used alongside whichever one the user picks — see generation/llm_models.py.
# Update these when a provider deprecates or renames a model; no code change needed.
_split_csv = lambda value: [v.strip() for v in value.split(",") if v.strip()]

GROQ_UI_MODELS = _split_csv(os.environ.get("GROQ_UI_MODELS", "openai/gpt-oss-20b,openai/gpt-oss-120b"))
GROQ_REASONING_MODEL = os.environ.get("GROQ_REASONING_MODEL", "openai/gpt-oss-120b")

GEMINI_UI_MODELS = _split_csv(os.environ.get("GEMINI_UI_MODELS", "models/gemini-3.8-flash,models/gemini-3.5-flash-lite"))
GEMINI_REASONING_MODEL = os.environ.get("GEMINI_REASONING_MODEL", "models/gemini-3.8-flash")

DEFAULT_UI_MODEL = os.environ.get("DEFAULT_UI_MODEL", "groq:openai/gpt-oss-20b")

# ========================================
# EMAIL (OTP delivery)
# ========================================

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.environ.get("EMAIL_HOST")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 587))
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True") == "True"
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)

# ========================================
# EMAIL OTP SIGN-IN
# ========================================

OTP_LENGTH = 6
OTP_TTL_MINUTES = 3
OTP_MAX_REQUESTS_PER_WINDOW = 5
OTP_RATE_LIMIT_WINDOW_HOURS = 3
OTP_MAX_VERIFY_ATTEMPTS = 5

# ========================================
# CELERY (async OTP email delivery)
# ========================================

CELERY_BROKER_URL = os.environ.get("REDIS_URL", "redis://127.0.0.1:6379/1")
# No result backend — OTP emails are fire-and-forget, nothing ever reads a
# task's return value, so there's nothing worth paying a backend round-trip for.
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE

# REDIS_URL can be a managed TLS instance (rediss://); without this, kombu
# silently falls back to an unverified TLS connection and logs a warning
# on every connect — this makes that explicit instead of implicit.
if CELERY_BROKER_URL.startswith("rediss://"):
    import ssl
    CELERY_BROKER_USE_SSL = {"ssl_cert_reqs": ssl.CERT_NONE}

# ========================================
# LOGGING (STRUCTLOG)
# ========================================

import structlog

structlog.configure(
    processors=[
        structlog.contextvars.merge_contextvars,
        structlog.processors.add_log_level,
        structlog.processors.StackInfoRenderer(),
        structlog.dev.set_exc_info,
        structlog.processors.TimeStamper(fmt="iso"),
        structlog.processors.JSONRenderer(),
    ],
    logger_factory=structlog.PrintLoggerFactory(),
    cache_logger_on_first_use=True,
)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": {
            "()": structlog.stdlib.ProcessorFormatter,
            "processor": structlog.processors.JSONRenderer(),
        },
        "plain": {
            "()": structlog.stdlib.ProcessorFormatter,
            "processor": structlog.dev.ConsoleRenderer(),
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "json",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}

DISCORD_WEBHOOK = os.environ.get("DISCORD_WEBHOOK")

# ========================================
# ERROR MONITORING (SENTRY)
# ========================================

SENTRY_DSN = os.environ.get("SENTRY_DSN")

if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        environment=APP_MODE,
        traces_sample_rate=0.1,
        send_default_pii=False,
    )
