"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta
import dj_database_url


load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

APP_MODE = str(os.environ.get("APP_MODE", 'Development'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False") == "True"

ALLOWED_HOSTS = ['*']

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "https://dburst-ui-generator.vercel.app",
    "http://localhost:5173",
    "https://localhost:5173",
]

CSRF_TRUSTED_ORIGINS = [
    "https://dburst-ui-generator.vercel.app",
    "https://dburst-ui-generator.onrender.com",
    "http://localhost:5173",
    "https://localhost:5173",
]
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "ngrok-skip-browser-warning",
]

# 1 day for access, 7 days for refresh
ACCESS_TOKEN_EXPIRY = 86400
REFRESH_TOKEN_EXPIRY = 604800

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # local apps
    'users',
    'projects',
    'generation',
    'patching',
    'feedback',
    
    # third party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework.authtoken',
    'corsheaders',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'dj_rest_auth',
    'dj_rest_auth.registration',
    # Enables runserver_plus and other Django extension commands.
    'django_extensions',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.environ.get("DATABASE_URL")

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(default=DATABASE_URL)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    # NOTE: ROTATE_REFRESH_TOKENS + BLACKLIST_AFTER_ROTATION require
    # 'rest_framework_simplejwt.token_blacklist' in INSTALLED_APPS and
    # running its migrations. Disabled until that is set up.
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': True,
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'config.authentication.CookieJWTAuthentication', 
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

AUTH_USER_MODEL = "users.User"

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1", 
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CLOSE_CONNECTION": True,
        }
    }
}

# ========================================
# SESSION CONFIGURATION (REDIS-BACKED)
# ========================================

# Use Redis for session storage
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

# Session Security Settings
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = True  # Set to True for HTTPS (ngrok)
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookie
SESSION_COOKIE_SAMESITE = 'None'  # Allow cross-site cookies
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_NAME = 'dburst_sessionid'  # Custom session cookie name
SESSION_COOKIE_PATH = '/'
SESSION_COOKIE_DOMAIN = None  # Use default domain

# Session Timeout Settings
SESSION_COOKIE_AGE = 86400 * 7  # 7 days (in seconds)
SESSION_SAVE_EVERY_REQUEST = False  # Only save if session modified
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Persist sessions

# Session Serialization
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer'

# ========================================
# CACHE TIMEOUT SETTINGS
# ========================================

# Cache timeouts for different data types
CACHE_TTL = {
    'generation_schema': 86400 * 3,  # 3 days
    'generation_code': 86400 * 3,    # 3 days
    'generation_meta': 86400 * 3,    # 3 days
    'patches': 86400 * 7,            # 7 days
    'session': 86400 * 7,            # 7 days
    'user_profile': 3600,            # 1 hour
    'project_list': 300,             # 5 minutes
}

# ========================================
# OAUTH & API KEYS
# ========================================

GOOGLE_CLIENT_ID = os.environ.get("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = os.environ.get("GOOGLE_CLIENT_SECRET")

GITHUB_CLIENT_ID = os.environ.get("GITHUB_CLIENT_ID")
GITHUB_CLIENT_SECRET = os.environ.get("GITHUB_CLIENT_SECRET")

# Whitelisted redirect URIs — backend validates against these.
# Add your production URL and any local dev URLs here.
_google_uris = os.environ.get(
    "GOOGLE_ALLOWED_REDIRECT_URIS",
    "postmessage,"
    "http://localhost:5173/auth/google/callback,"
    "https://localhost:5173/auth/google/callback,"
    "https://dburst-ui-generator.onrender.com/auth/google/callback,"
    "https://dburst-ui-generator.vercel.app/auth/google/callback"
)
GOOGLE_ALLOWED_REDIRECT_URIS = [u.strip() for u in _google_uris.split(",") if u.strip()]

_github_uris = os.environ.get(
    "GITHUB_ALLOWED_REDIRECT_URIS",
    "http://localhost:5173/auth/github/callback,"
    "https://localhost:5173/auth/github/callback,"
    "https://dburst-ui-generator.onrender.com/auth/github/callback,"
    "https://dburst-ui-generator.vercel.app/auth/github/callback"
)
GITHUB_ALLOWED_REDIRECT_URIS = [u.strip() for u in _github_uris.split(",") if u.strip()]

GROQ_AI_API_KEY = os.environ.get("GROQ_AI_API_KEY")
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")

# ========================================
# LOGGING (STRUCTLOG)
# ========================================

import structlog

structlog.configure(
    processors=[
        structlog.contextvars.merge_contextvars,
        structlog.processors.add_log_level,
        structlog.processors.StackInfoRenderer(),
        structlog.dev.set_exc_info,
        structlog.processors.TimeStamper(fmt="iso"),
        structlog.processors.JSONRenderer(),
    ],
    logger_factory=structlog.PrintLoggerFactory(),
    cache_logger_on_first_use=True,
)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": {
            "()": structlog.stdlib.ProcessorFormatter,
            "processor": structlog.processors.JSONRenderer(),
        },
        "plain": {
            "()": structlog.stdlib.ProcessorFormatter,
            "processor": structlog.dev.ConsoleRenderer(),
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "json",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}

DISCORD_WEBHOOK = os.environ.get("DISCORD_WEBHOOK")
