import { useMemo } from 'react';
import { useWebContainer } from './useWebContainer';
import { WebContainerStatus } from './WebContainerStatus';
import { buildReactViteProject } from './fileSystemUtils';

// Import auth as a side-effect — initialises WebContainer auth on first use
import './webcontainerAuth';

interface WebContainerPreviewProps {
    /** Raw React component code string generated by DBurst */
    code: string | undefined | null;
}

/**
 * Renders the generated code inside a real Vite dev server
 * running in-browser via StackBlitz WebContainer.
 *
 * Performance strategy:
 * - `files` (full FileSystemTree) is memoised with a stable reference so
 *   it only changes when the project structure changes (not on every keystroke).
 * - `appCode` (the raw code string) is passed separately, allowing the hook
 *   to hot-swap src/App.tsx via wc.fs.writeFile() without re-running npm install.
 */

/**
 * The AI sometimes generates invalid Tailwind arbitrary-value syntax like
 * `bg-#ec4899` or `from-#0f172a`. Tailwind requires square brackets:
 * `bg-[#ec4899]`. This function fixes them before mounting in WebContainer.
 */
function preprocessCode(code: string): string {
    // Match any Tailwind colour-related utility followed by -#<hex>
    return code.replace(
        /\b(bg|text|from|via|to|border|ring|fill|stroke|shadow|accent|caret|divide|outline|placeholder|decoration|gradient)-#([0-9a-fA-F]{3,8})\b/g,
        '$1-[#$2]'
    );
}

export function WebContainerPreview({ code }: WebContainerPreviewProps) {
    // Preprocess the code once
    const processedCode = useMemo(() => {
        if (!code) return null;
        return preprocessCode(code);
    }, [code]);

    // Build the scaffold file tree WITHOUT the App.tsx code — this stays
    // stable as long as the project structure doesn't change, so it won't
    // trigger a full reinstall on every code update.
    // We pass a placeholder for App.tsx; the hot-update effect will write the real code.
    const files = useMemo(() => {
        if (!processedCode) return null;
        // Build the full project with the code included for the initial mount.
        // On subsequent updates, only appCode will change and the hot-update
        // path in useWebContainer will handle it via wc.fs.writeFile().
        return buildReactViteProject(processedCode);
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []); // ← intentionally empty: build once on mount, then use hot-update

    const { status, previewUrl, logs, error, reload } = useWebContainer({
        files,
        appCode: processedCode,
    });

    // No code yet — prompt user to generate
    if (!code) {
        return (
            <div className="flex-1 flex flex-col items-center justify-center text-slate-400 gap-3">
                <span className="text-4xl">🚀</span>
                <p className="text-sm">Generate a UI to see the live preview here.</p>
            </div>
        );
    }

    return (
        <div className="flex-1 flex flex-col overflow-hidden">
            {/* Status bar */}
            <WebContainerStatus
                status={status}
                logs={logs}
                error={error}
                onReload={reload}
            />

            {/* Preview area */}
            <div className="flex-1 relative overflow-hidden bg-slate-100">
                {/* Loading overlay */}
                {status !== 'ready' && status !== 'error' && (
                    <div className="absolute inset-0 flex flex-col items-center justify-center bg-slate-900/90 z-10 gap-4">
                        <BootingSpinner status={status} />
                    </div>
                )}

                {/* Error screen */}
                {status === 'error' && (
                    <div className="absolute inset-0 flex flex-col items-center justify-center bg-slate-900/90 z-10 gap-4 p-6">
                        <span className="text-4xl">⚠️</span>
                        <p className="text-red-400 text-sm font-mono text-center max-w-md">{error}</p>
                        <button
                            onClick={reload}
                            className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white text-sm rounded transition"
                        >
                            Try Again
                        </button>
                    </div>
                )}

                {/* The actual preview iframe */}
                {previewUrl && (
                    <iframe
                        src={previewUrl}
                        title="DBurst Live Preview"
                        className="absolute inset-0 w-full h-full border-0"
                        allow="cross-origin-isolated"
                    />
                )}
            </div>
        </div>
    );
}

// ─── Internal sub-component ──────────────────────────────────────────────────

const BOOT_MESSAGES: Record<string, string> = {
    idle: 'Preparing…',
    booting: 'Booting WebContainer',
    mounting: 'Mounting project files',
    installing: 'Installing dependencies (first time only…)',
    starting: 'Starting Vite dev server',
    updating: 'Applying code update…',
    ready: 'Ready!',
    error: '',
};

function BootingSpinner({ status }: { status: string }) {
    return (
        <div className="flex flex-col items-center gap-3 text-slate-300">
            {/* Spinner */}
            <svg
                className="animate-spin h-10 w-10 text-blue-400"
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
            >
                <circle
                    className="opacity-25"
                    cx="12" cy="12" r="10"
                    stroke="currentColor" strokeWidth="4"
                />
                <path
                    className="opacity-75"
                    fill="currentColor"
                    d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"
                />
            </svg>

            <p className="text-sm font-medium">{BOOT_MESSAGES[status] ?? 'Loading…'}</p>
            {status === 'installing' && (
                <p className="text-xs text-slate-500">
                    Packages install once and are cached — subsequent loads are instant ⚡
                </p>
            )}
        </div>
    );
}
